/*
Enter your query here.
Please append a semicolon ";" at the end of the query and enter your query in a single line to avoid error.
*/

SELECT C.COMPANY_CODE, C.FOUNDER, L.TOTAL_LEAD_MANAGERS, TOTAL_SENIOR_MANAGERS, TOTAL_MANAGERS, TOTAL_EMPLOYEES 
FROM 
COMPANY C INNER JOIN
(
    SELECT COUNT(DISTINCT LEAD_MANAGER_CODE) AS TOTAL_LEAD_MANAGERS, COMPANY_CODE FROM LEAD_MANAGER
    GROUP BY COMPANY_CODE
 ) L
 ON C.COMPANY_CODE = L.COMPANY_CODE
 INNER JOIN 
 (
    SELECT COUNT(DISTINCT SENIOR_MANAGER_CODE) AS TOTAL_SENIOR_MANAGERS, COMPANY_CODE FROM SENIOR_MANAGER
 GROUP BY COMPANY_CODE ) S
 ON C.COMPANY_CODE = S.COMPANY_CODE
 INNER JOIN 
 (
    SELECT COUNT(DISTINCT MANAGER_CODE) AS TOTAL_MANAGERS, COMPANY_CODE FROM MANAGER
 GROUP BY COMPANY_CODE ) M
  ON C.COMPANY_CODE = M.COMPANY_CODE
 INNER JOIN 
 (
    SELECT COUNT(DISTINCT EMPLOYEE_CODE) AS TOTAL_EMPLOYEES, COMPANY_CODE FROM EMPLOYEE
 GROUP BY COMPANY_CODE ) E
  ON C.COMPANY_CODE = E.COMPANY_CODE
 ORDER BY COMPANY_CODE;
 
