DECLARE @MINV INT, @MAXV INT
SET @MINV = (SELECT MIN(LEN(CITY)) FROM STATION)
SET @MAXV = (SELECT MAX(LEN(CITY)) FROM STATION)

SELECT TOP 1 CITY, LEN(CITY) FROM STATION
WHERE LEN(CITY) = @MINV
ORDER BY CITY
SELECT TOP 1 CITY, LEN(CITY) FROM STATION
WHERE LEN(CITY) = @MAXV
ORDER BY CITY
--ORDER BY LEN(CITY) DESC, CITY ASC
